version: '3.2'

services:
  db.backend.dev:
    container_name: db.backend.dev
    image: mysql:5.7
    command: --max_allowed_packet=512M
    volumes:
      - mysql_dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    ports:
      - '3306:3306'

  api.backend.dev:
    container_name: api.backend.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
      - node_modules-backend:/usr/src/app/node_modules
    ports:
      - '3333:3333'

volumes:
  mysql_dev:
  node_modules-backend:
  node_modules-frontend:
