version: '3.2'

services:
  mongo.dev:
    container_name: mongo.dev
    image: mongo:4.2
    volumes:
      - mongo_dev:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none

  api.backend.dev:
    container_name: api.backend.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
      - node_modules-backend:/usr/src/app/node_modules
    ports:
      - "3333:3333"

volumes:
  mongo_dev:
  node_modules-backend: